# Site settings
email:
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-102571130-2
default_img:

# SEO
title: Melons
description: >- # this means to ignore newlines until "baseurl:"
  :watermelon: – A blog theme for Jekyll.
twitter:
  username:
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: favicon.ico
lang: 

# social
social:
  github: https://github.com/OrangeDugongo/Melons
    
# Profile settings
uno-name: Orange
uno-profile_img:  https://avatars0.githubusercontent.com/u/4928896?v=3&s=460
uno-profile: Computer engineering student at the University of the studies of sannio
uno-social:
  twitter:  https://twitter.com/Orange_dugongo
  instagram:  https://www.instagram.com/orange_dugongo/
  500px:  https://500px.com/orange_dugongo
  github: https://github.com/OrangeDugongo

due-name: Thomas
due-profile_img: https://unsplash.it/2000/1200?image=447
due-profile: Thomas Vaeth was born in New York, raised in Pennsylvania, and transplanted in Washington. He was a biochemist, but now he's a web developer at Urban Influence. He's also semi-decent at table tennis.
due-social:

# Sass
sass:
  style: compressed

# Build settings
markdown: kramdown
theme: minima
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-autoprefixer



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - screenshot
  - firebase.json # if you use firebase

